import {
  ResponsiveContainer,
  BarChart,
  CartesianGrid,
  XAxis,
  YAxis,
  Tooltip,
  Legend,
  Bar,
  AreaChart,
  Area,
  LineChart,
} from "recharts";
import { Card, CardHeader, CardContent } from "./ui/card";

const MonthlySummaryChart = ({
  monthlyData,
  selectedMonthYear,
  setSelectedMonthYear,
}) => {
  const kWhFormatter = (num) => {
    return (num / 1000).toFixed(1);
  };

  // Format date for axis label
  const formatDateforAxisLabel = (date) => {
    const year = date.slice(0, 4);
    const month = date.slice(4, 6);
    return month + "/" + year;
  };
  // Transform the data to match the expected format for the chart
  const transformedData = monthlyData
    .filter((item) => item.month.startsWith(selectedMonthYear.slice(0, 4))) // TO DO THIS SHOULD NOT BE HARDCODED TO 2023!!
    .map((item) => ({
      "Total Energy Generated": kWhFormatter(item.energyGenerated),
      date: formatDateforAxisLabel(item.month),
    }));

  // Find the highest value for Total Energy Generated
  const energyValues = transformedData.map((item) => {
    const value = parseFloat(item["Total Energy Generated"]) * 1.05;
    return Math.ceil(value / 100) * 100;
  });
  const yAxisLimit = Math.max(...energyValues);

  return (
    <Card className="w-full">
      <CardHeader>
        <h3 className="text-lg font-bold text-[#30AEBE]">
          Energy Generated by Month for {selectedMonthYear.slice(0, 4)}
        </h3>
      </CardHeader>
      <CardContent>
        <ResponsiveContainer width="100%" height={400}>
          <BarChart data={transformedData}>
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis dataKey="date" />
            <YAxis
              type="number"
              domain={[0, yAxisLimit]}
              label={{
                value: "kWh",
                position: "insideLeft",
                angle: "-90",
                offset: "0",
              }}
            />
            <Tooltip />
            <Legend />
            <Bar dataKey="Total Energy Generated" fill="#30AEBE" />
          </BarChart>
        </ResponsiveContainer>
      </CardContent>
    </Card>
  );
};

export default MonthlySummaryChart;
