import {
  ResponsiveContainer,
  BarChart,
  CartesianGrid,
  XAxis,
  YAxis,
  Tooltip,
  Legend,
  Bar,
  AreaChart,
  Area,
  LineChart,
} from "recharts";
import { Card, CardHeader, CardContent } from "./ui/card";

const kWhFormatter = (num) => {
  return (num / 1000).toFixed(1);
};

// Format date for axis label
const formatDateforAxisLabel = (date) => {
  const year = date.slice(0, 4);
  const month = date.slice(4, 6);
  return month + "/" + year;
};

const MonthlySummaryChart = ({ monthlyData }) => {
  // Transform the data to match the expected format for the chart
  const transformedData = monthlyData
    .filter((item) => item.month.startsWith("2023")) // TO DO THIS SHOULD NOT BE HARDCODED TO 2023!!
    .map((item) => ({
      "Total Energy Generated": kWhFormatter(item.energyGenerated),
      date: formatDateforAxisLabel(item.month),
    }));

  return (
    <Card className="w-full">
      <CardHeader>
        <h3 className="text-lg font-bold">
          Energy Generated by Month for 2023
        </h3>
      </CardHeader>
      <CardContent>
        <ResponsiveContainer width="100%" height={400}>
          <BarChart data={transformedData}>
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis dataKey="date" />
            <YAxis
              type="number"
              domain={[0, 600]}
              label={{
                value: "kWh",
                position: "insideLeft",
                angle: "-90",
                offset: "0",
              }}
            />
            <Tooltip />
            <Legend />
            <Bar dataKey="Total Energy Generated" fill="#0D9488" />
          </BarChart>
        </ResponsiveContainer>
      </CardContent>
    </Card>
  );
};

export default MonthlySummaryChart;
