import {
  ResponsiveContainer,
  BarChart,
  CartesianGrid,
  XAxis,
  YAxis,
  Tooltip,
  Legend,
  Bar,
} from "recharts";
import { Card, CardHeader, CardContent } from "./ui/card";

const YearlySummaryChart = ({ yearlyData }) => {
  const kWhFormatter = (num) => {
    return (num / 1000).toFixed(1);
  };

  // Transform the data to match the expected format for the chart
  const transformedData = yearlyData.map((item) => ({
    "Total Energy Generated": kWhFormatter(item.energyGenerated),
    date: item.year,
  }));

  // Find the highest value for Total Energy Generated
  const energyValues = transformedData.map((item) => {
    const value = parseFloat(item["Total Energy Generated"]) * 1.05;
    return Math.ceil(value / 500) * 500;
  });
  const yAxisLimit = Math.max(...energyValues);

  return (
    <Card className="w-full">
      <CardHeader>
        <h3 className="text-lg font-bold text-[#30AEBE]">
          Energy Generated by Year
        </h3>
      </CardHeader>
      <CardContent>
        <ResponsiveContainer width="100%" height={400}>
          <BarChart data={transformedData}>
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis dataKey="date" />
            <YAxis
              domain={[0, yAxisLimit]}
              label={{
                value: "kWh",
                position: "insideLeft",
                angle: "-90",
                offset: "0",
              }}
            />
            <Tooltip />
            <Legend />
            <Bar dataKey="Total Energy Generated" fill="#30AEBE" />
          </BarChart>
        </ResponsiveContainer>
      </CardContent>
    </Card>
  );
};

export default YearlySummaryChart;
